name: task_voting
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  vote: ^2.1.0
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  collection: ^1.16.0
  meta: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_system_access:
    git:
      url: https://github.com/juancastillo0/file_system_access_web.git
  stack_portal:
    git:
      url: https://github.com/juancastillo0/stack_portal.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - packages/file_system_access/assets/file_persistence.js
